export const PCOS_DIET_PLAN = {
    principles: [
        'Prioritize low-glycemic, high-fiber carbohydrates',
        'Add protein in every meal to reduce insulin spikes',
        'Use anti-inflammatory fats (nuts, seeds, olive oil)',
        'Stay consistent with meal timing and hydration',
    ],
    includeFoods: [
        'Leafy greens',
        'Lentils & beans',
        'Millets / oats',
        'Greek yogurt / curd',
        'Eggs / paneer / tofu',
        'Berries & apples',
        'Flaxseed & chia',
        'Nuts (almond/walnut)',
    ],
    limitFoods: [
        'Refined sugar',
        'White bread/maida',
        'Sugary drinks',
        'Deep fried foods',
        'Processed snacks',
        'High trans-fat foods',
    ],
    weeklyPlan: [
        {
            day: 'Day 1',
            breakfast: 'Oats + chia + nuts',
            lunch: 'Millet roti + dal + salad',
            snack: 'Apple + peanuts',
            dinner: 'Grilled paneer/tofu + veggies',
        },
        {
            day: 'Day 2',
            breakfast: 'Veg omelette / tofu scramble',
            lunch: 'Brown rice + rajma + cucumber',
            snack: 'Greek yogurt + seeds',
            dinner: 'Mixed veg soup + chickpea salad',
        },
        {
            day: 'Day 3',
            breakfast: 'Besan chilla + mint curd',
            lunch: 'Quinoa bowl + lentils + greens',
            snack: 'Roasted chana',
            dinner: 'Paneer bhurji + sautéed veggies',
        },
        {
            day: 'Day 4',
            breakfast: 'Overnight oats + berries',
            lunch: 'Roti + chole + salad',
            snack: 'Buttermilk + walnuts',
            dinner: 'Tofu stir-fry + clear soup',
        },
        {
            day: 'Day 5',
            breakfast: 'Idli + sambar + veggies',
            lunch: 'Millet khichdi + curd',
            snack: 'Pear + seeds mix',
            dinner: 'Grilled fish/tofu + steamed veg',
        },
        {
            day: 'Day 6',
            breakfast: 'Moong dal cheela + chutney',
            lunch: 'Brown rice + dal + beet salad',
            snack: 'Sprout chaat',
            dinner: 'Veg stew + paneer cubes',
        },
        {
            day: 'Day 7',
            breakfast: 'Upma with veggies + nuts',
            lunch: 'Roti + mixed dal + greens',
            snack: 'Yogurt + flaxseed',
            dinner: 'Light soup + chickpea tikki',
        },
    ],
};
